sudo: required

language: minimal

services:
        - docker

before_install:
        - ./tests/TestHTTP.sh

script:
        - wget -O - -q --post-data=trigger "$DOCKERHUB_TRIGGER_URL" > /dev/null 2>&1

